### ISSUE TITLE
Process start error : Parameter -n needs a numeric value

### ISSUE THREAD

**Issue by ggouttesol** [jcaillon/3P#159]
### Description of the Issue
Just after lauching deployment, several error message boxes pop up, all with the same Progress error message.

![3p](https://cloud.githubusercontent.com/assets/23432181/24693652/e3096d88-19de-11e7-8962-0aa7ff6acad2.PNG)

After closing four message boxes, 3P show a critical error : 
![3p_2](https://cloud.githubusercontent.com/assets/23432181/24693796/a3a38cc2-19df-11e7-9c10-907c3cec9d58.PNG)

### Steps to Reproduce the Issue
1. Verify that the connection to the database of the selected environment is OK
2. Verify that the source directory and the deployment directory are OK
3. Click the button "Start Deploying".

### Debug Information
3P Version : 1.7.4 beta
N++ version : 7.3.2 32 bits

**Comment by ggouttesolard** [comment]
I have a similar error when I try to access the DataDigger through the "ALT+D -> Explore your Data" menu :
![datadigger](https://cloud.githubusercontent.com/assets/23432181/24694926/134111ae-19e4-11e7-9e5b-34ced314505f.PNG)
![datadigger2](https://cloud.githubusercontent.com/assets/23432181/24694935/1967122c-19e4-11e7-9f43-c97a691e5c98.PNG)

**Comment by jcaillon** [comment]
Hi, it looks like a progress error, did you set additionnal prowin parameters here by any chance? :

![image](https://cloud.githubusercontent.com/assets/11553075/24696070/79221d0c-19e8-11e7-9f3a-417d3d1164a3.png)

**Comment by ggouttesolard** [comment]
No, unfortunately...

![image](https://cloud.githubusercontent.com/assets/23432181/24696824/221225ea-19eb-11e7-84f2-6fae17f65b3e.png)

**Comment by jcaillon** [comment]
Damn; I found the bug. I now use the -nosplash parameter to start a prowin session. Doesn't work prior to version 11.6... My bad :/

**Comment by jcaillon** [comment]
I've updated the latest release artifacts to correct this issue. If you encounter it, manually replace the plugin files with the new files [here](https://github.com/jcaillon/3P/releases/tag/v1.7.4)!

I keep this issue open for now (even if it is corrected)

**Comment by RichardWeyn** [comment]
Hello. I've got the same problem (1.7.4 BETA). I've tried to update my 3P.dll and 3P.pdb manually, but the problem remains. I can't use neither the Prolint nor the Data Digger tool and the Data Administrator.
The same message appears and the critical error is : 
![image](https://cloud.githubusercontent.com/assets/19261812/24850069/e8b054d8-1dce-11e7-9976-8245351c2a21.png)


I don't have extra parameters
![image](https://cloud.githubusercontent.com/assets/19261812/24850112/08b84128-1dcf-11e7-954d-21a616ed6673.png)
